services:
  core:
    container_name: football-core
    build: 
      context: ./docker/core
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./scripts/core-app:/app
    env_file:
      - scripts/core-app/.env
    environment:
      - DOCKER_ENV=1
      - DISPLAY=:99
    shm_size: '2gb'
    privileged: true
    cap_add:
      - SYS_ADMIN
    depends_on:
      - db

  db:
    # image: postgres
    # container_name: postgres
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: football-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: football
    ports:
      - "5432:5432"
    volumes:
      - footballdata:/var/lib/postgresql/data
      - ./scripts/postgres:/scripts

  ui:
    container_name: football-ui
    build:
      context: ./docker/streamlit
      dockerfile: Dockerfile
    env_file:
      - scripts/streamlit-app/.env
    environment:
      - WATCHDOG_TIMEOUT=60
      - STREAMLIT_SERVER_WATCH_DIRS=true
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    ports:
      - "8501:8501"
    volumes:
      - ./scripts/streamlit-app:/app/streamlit-app

volumes:
  footballdata: