services:
  core:
    container_name: core
    build: 
      context: ./docker/core
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./scripts/core-app:/app
    env_file:
      - scripts/core-app/.env
    environment:
      - DOCKER_ENV=1
      - DISPLAY=:99
    shm_size: '2gb'
    privileged: true
    cap_add:
      - SYS_ADMIN
    depends_on:
      - postgres-football

  postgres-football:
    # image: postgres
    build:
      context: ./docker/postgres-football
      dockerfile: Dockerfile
    container_name: postgres-football
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: football
    ports:
      - "5432:5432"
    volumes:
      - footballdata:/var/lib/postgresql/data
      - ./scripts/postgres:/scripts

  pgadmin4:
    build:
      context: ./docker/pgadmin4
      dockerfile: Dockerfile
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
    volumes:
      - pgadmin4:/var/lib/pgadmin
      - ./docker/pgadmin4/servers.json:/pgadmin4/servers.json
  
  postgres-pgadmin:
    build:
      context: ./docker/postgres-pgadmin
      dockerfile: Dockerfile
    container_name: postgres-pgadmin
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pgadmindb
    ports:
      - "5433:5432"

  
  streamlit:
    container_name: streamlit
    build:
      context: ./docker/streamlit
      dockerfile: Dockerfile
    env_file:
      - scripts/streamlit-app/.env
    environment:
      - WATCHDOG_TIMEOUT=60
      - STREAMLIT_SERVER_WATCH_DIRS=true
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    ports:
      - "8501:8501"
    volumes:
      - ./scripts/streamlit-app:/app/streamlit-app

  superset:
    container_name: superset
    build:
      context: ./docker/superset
      dockerfile: Dockerfile
    environment:
      - SUPERSET_SECRET_KEY=12345
      - DATABASE_DB=football
      - DATABASE_HOST=postgres-football
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PORT=5432
      - SQLALCHEMY_DATABASE_URI=${FOOTBALL_DATABASE_URI}
    ports:
      - "8088:8088"


volumes:
  footballdata:
  pgadmin4:
