services:
  web:
    # container_name: web
    build: 
      context: ./docker/web-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./scripts/web-app:/app
    env_file:
      - scripts/web-app/.env
    environment:
      - DOCKER_ENV=1
      - DISPLAY=:99
    shm_size: '2gb'
    privileged: true
    cap_add:
      - SYS_ADMIN
    depends_on:
      - db

  db:
    # image: postgres
    # container_name: postgres
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: football
    ports:
      - "5432:5432"
    volumes:
      - footballdata:/var/lib/postgresql/data
      - ./scripts/postgres:/scripts

volumes:
  footballdata: