version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DOCKER_ENV=1
      - DISPLAY=:99
    shm_size: '2gb'
    privileged: true
    cap_add:
      - SYS_ADMIN
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: football
    ports:
      - "5432:5432"
    volumes:
      - footballdata:/var/lib/postgresql/data

volumes:
  footballdata:
